// skills/init/scripts/gen-config.mjs
//
// [Model Limit Assumption]
// LLM은 config 파일 형식을 일관되게 생성하지 못할 수 있다.
// → 템플릿 기반으로 결정론적 config.yaml 생성.
//
// [Exit Protocol]
// exit(0) = 생성 완료
// exit(1) = 런타임 에러

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectDir = process.env.CLAUDE_PROJECT_DIR || '.';
const pluginRoot = process.env.CLAUDE_PLUGIN_ROOT || resolve(__dirname, '../../..');

// 환경변수로 설정 전달
const mode = process.env.HARNESS_MODE || 'standard';
const language = process.env.HARNESS_LANGUAGE || '';
const framework = process.env.HARNESS_FRAMEWORK || '';

function main() {
  const configPath = resolve(projectDir, '.harness/config.yaml');

  if (existsSync(configPath)) {
    process.stderr.write('gen-config: config.yaml 이미 존재 — skip\n');
    process.stdout.write(JSON.stringify({ status: 'exists', path: configPath }) + '\n');
    process.exit(0);
  }

  // 템플릿 로드
  const tmplPath = resolve(pluginRoot, 'skills/init/templates/config.yaml.tmpl');
  let template;

  if (existsSync(tmplPath)) {
    template = readFileSync(tmplPath, 'utf8');
  } else {
    // 템플릿이 없으면 인라인 기본값
    template = defaultTemplate();
  }

  // 변수 치환
  const config = template
    .replace(/\{\{mode\}\}/g, mode)
    .replace(/\{\{language\}\}/g, language || 'auto')
    .replace(/\{\{framework\}\}/g, framework || 'auto');

  writeFileSync(configPath, config, 'utf8');
  process.stderr.write(`gen-config: config.yaml 생성 완료 (mode: ${mode})\n`);
  process.stdout.write(JSON.stringify({ status: 'created', mode, path: configPath }) + '\n');
  process.exit(0);
}

function defaultTemplate() {
  return `# Harness Configuration
# Generated by /harness:init

# Workflow mode: standard | prototype | explore
mode: {{mode}}

# Project stack (auto-detected or manually set)
stack:
  language: {{language}}
  framework: {{framework}}

# Workflow settings
workflow:
  right_size: auto

# Testing settings
testing:
  coverage:
    line_min: 80
    branch_min: 70

# Audit settings
audit:
  enabled: true
  rotate_mb: 10
  retention_days: 90
`;
}

main();
